### ISSUE TITLE
Unrecognized function or variable 'covupd'

### ISSUE THREAD

**Issue by BrunoMM2** [benatOliveira/MCMC_GCA#1]
I downloaded the full zip with all the code and when I run the 'mcmc_wrapper.m' I get the error:
Unrecognized function or variable 'covupd'.

Error in amrun (line 254)
            [chaincov,chainmean,wsum] = covupd(chain((lasti+1):isimu,:),1, ...

That 'covupd' function I saw on the annotations of the 'amrun' that it is based on the matlab DRAM code by M. Laine. but the function 'covupd' is not defined here, so, I have to download it from mjlaine/mcmcstat: MCMC toolbox for Matlab (github.com) ? 
Is this a pre-requirement and it is written somewhere and I didn´t see it ?

**Comment by benatOliveira** [comment]
added in the new release
