### ISSUE TITLE
Unrecognized function or variable 'major_creator_new'

### ISSUE THREAD

**Issue by BrunoMM2** [benatOliveira/MCMC_GCA#2]
I have another issue after https://github.com/benatOliveira/MCMC_GCA/issues/1#issue-1469821295 because I downloaded the 'covupd.m' from [mjlaine/mcmcstat: MCMC toolbox for Matlab (github.com)](https://github.com/mjlaine/mcmcstat) and this seems to solve that issue but when I run again the code I get this error:

Unrecognized function or variable 'major_creator_new'.

Error in plots_results_RGR (line 153)
[SiO2,Al2O3,FeOt,MnO,MgO,CaO,Na2O,Cr2O3,TiO2] =major_creator_new(Al2O3_ox,MnO_ox,Na2O_ox,Cr2O3_ox,TiO2_ox);

So I have four of the fifth figures from the 'plots_results_RGR' but I don´t know know what I have to do to solve this one

**Comment by benatOliveira** [comment]
added in the new release
